//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopUI.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _MenuAboutApp.
        /// </summary>
        public static string AboutAppMenu {
            get {
                return ResourceManager.GetString("AboutAppMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _AppReleaseNotesErr.
        /// </summary>
        public static string AppReleaseNotesErr {
            get {
                return ResourceManager.GetString("AppReleaseNotesErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _AppReleaseNotesLoad.
        /// </summary>
        public static string AppReleaseNotesLoad {
            get {
                return ResourceManager.GetString("AppReleaseNotesLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsAppMain.
        /// </summary>
        public static string AppSettingsMain {
            get {
                return ResourceManager.GetString("AppSettingsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _AppVersion.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ButtonDetailOfTournament.
        /// </summary>
        public static string ButtonDetailOfTournament {
            get {
                return ResourceManager.GetString("ButtonDetailOfTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ButtonGameOn.
        /// </summary>
        public static string ButtonGameOn {
            get {
                return ResourceManager.GetString("ButtonGameOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ButtonTournament.
        /// </summary>
        public static string ButtonTournament {
            get {
                return ResourceManager.GetString("ButtonTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ButtonTraining.
        /// </summary>
        public static string ButtonTraining {
            get {
                return ResourceManager.GetString("ButtonTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DartboardClear.
        /// </summary>
        public static string DartboardClear {
            get {
                return ResourceManager.GetString("DartboardClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DartboardConfirm.
        /// </summary>
        public static string DartboardConfirm {
            get {
                return ResourceManager.GetString("DartboardConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DartboardCurrentRound.
        /// </summary>
        public static string DartboardCurrentRound {
            get {
                return ResourceManager.GetString("DartboardCurrentRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DartboardDouble.
        /// </summary>
        public static string DartboardDouble {
            get {
                return ResourceManager.GetString("DartboardDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DartboardMain.
        /// </summary>
        public static string DartboardMain {
            get {
                return ResourceManager.GetString("DartboardMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DartboardOutside.
        /// </summary>
        public static string DartboardOutside {
            get {
                return ResourceManager.GetString("DartboardOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DartboardSingle.
        /// </summary>
        public static string DartboardSingle {
            get {
                return ResourceManager.GetString("DartboardSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DartboardThrown.
        /// </summary>
        public static string DartboardThrown {
            get {
                return ResourceManager.GetString("DartboardThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DartboardTreble.
        /// </summary>
        public static string DartboardTreble {
            get {
                return ResourceManager.GetString("DartboardTreble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DartboardUpNext.
        /// </summary>
        public static string DartboardUpNext {
            get {
                return ResourceManager.GetString("DartboardUpNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DuelError.
        /// </summary>
        public static string DuelError {
            get {
                return ResourceManager.GetString("DuelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DuelFirstTeam.
        /// </summary>
        public static string DuelFirstTeam {
            get {
                return ResourceManager.GetString("DuelFirstTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DuelFirstTo.
        /// </summary>
        public static string DuelFirstTo {
            get {
                return ResourceManager.GetString("DuelFirstTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DuelPlayerFour.
        /// </summary>
        public static string DuelPlayerFour {
            get {
                return ResourceManager.GetString("DuelPlayerFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DuelPlayerOne.
        /// </summary>
        public static string DuelPlayerOne {
            get {
                return ResourceManager.GetString("DuelPlayerOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DuelPlayerThree.
        /// </summary>
        public static string DuelPlayerThree {
            get {
                return ResourceManager.GetString("DuelPlayerThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DuelPlayerTwo.
        /// </summary>
        public static string DuelPlayerTwo {
            get {
                return ResourceManager.GetString("DuelPlayerTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DuelSecondTeam.
        /// </summary>
        public static string DuelSecondTeam {
            get {
                return ResourceManager.GetString("DuelSecondTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DuelSetMainText.
        /// </summary>
        public static string DuelSetMainText {
            get {
                return ResourceManager.GetString("DuelSetMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DuelSetMatch.
        /// </summary>
        public static string DuelSetMatch {
            get {
                return ResourceManager.GetString("DuelSetMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DuelSetNumberOfLegs.
        /// </summary>
        public static string DuelSetNumberOfLegs {
            get {
                return ResourceManager.GetString("DuelSetNumberOfLegs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DuelSetNumberOfSets.
        /// </summary>
        public static string DuelSetNumberOfSets {
            get {
                return ResourceManager.GetString("DuelSetNumberOfSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DuelSetSets.
        /// </summary>
        public static string DuelSetSets {
            get {
                return ResourceManager.GetString("DuelSetSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DuelWins.
        /// </summary>
        public static string DuelWins {
            get {
                return ResourceManager.GetString("DuelWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _MainName.
        /// </summary>
        public static string MainName {
            get {
                return ResourceManager.GetString("MainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _MenuDartboard.
        /// </summary>
        public static string MenuDartboard {
            get {
                return ResourceManager.GetString("MenuDartboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _MenuMusic.
        /// </summary>
        public static string MusicMMenu {
            get {
                return ResourceManager.GetString("MusicMMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _NumPlayers.
        /// </summary>
        public static string NumPlayers {
            get {
                return ResourceManager.GetString("NumPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _NumScore.
        /// </summary>
        public static string NumScore {
            get {
                return ResourceManager.GetString("NumScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _MenuPlay.
        /// </summary>
        public static string PlayMenu {
            get {
                return ResourceManager.GetString("PlayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ProgName.
        /// </summary>
        public static string ProgName {
            get {
                return ResourceManager.GetString("ProgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsCancel.
        /// </summary>
        public static string SettingsCancel {
            get {
                return ResourceManager.GetString("SettingsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsDefault.
        /// </summary>
        public static string SettingsDefault {
            get {
                return ResourceManager.GetString("SettingsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsLang.
        /// </summary>
        public static string SettingsLang {
            get {
                return ResourceManager.GetString("SettingsLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _MenuSettings.
        /// </summary>
        public static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsNameColors.
        /// </summary>
        public static string SettingsNameAndColors {
            get {
                return ResourceManager.GetString("SettingsNameAndColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsOther.
        /// </summary>
        public static string SettingsOthers {
            get {
                return ResourceManager.GetString("SettingsOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsPlayerColor.
        /// </summary>
        public static string SettingsPlayerColor {
            get {
                return ResourceManager.GetString("SettingsPlayerColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsPlayerName.
        /// </summary>
        public static string SettingsPlayerName {
            get {
                return ResourceManager.GetString("SettingsPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsSave.
        /// </summary>
        public static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsSoundEffects.
        /// </summary>
        public static string SettingsSoundEffects {
            get {
                return ResourceManager.GetString("SettingsSoundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsStartupMusic.
        /// </summary>
        public static string SettingsStartupMusic {
            get {
                return ResourceManager.GetString("SettingsStartupMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsTheme.
        /// </summary>
        public static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsThemeDark.
        /// </summary>
        public static string SettingsThemeDark {
            get {
                return ResourceManager.GetString("SettingsThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsThemeLight.
        /// </summary>
        public static string SettingsThemeLight {
            get {
                return ResourceManager.GetString("SettingsThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsThemeSystem.
        /// </summary>
        public static string SettingsThemeSystem {
            get {
                return ResourceManager.GetString("SettingsThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsTransparency.
        /// </summary>
        public static string SettingsTransparency {
            get {
                return ResourceManager.GetString("SettingsTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsTransparencyIntensity.
        /// </summary>
        public static string SettingsTransparencyIntensity {
            get {
                return ResourceManager.GetString("SettingsTransparencyIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsUpdate.
        /// </summary>
        public static string SettingsUpdate {
            get {
                return ResourceManager.GetString("SettingsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SettingsWallpaper.
        /// </summary>
        public static string SettingsWallpaper {
            get {
                return ResourceManager.GetString("SettingsWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _StatisticsAverage.
        /// </summary>
        public static string StatisticsAverage {
            get {
                return ResourceManager.GetString("StatisticsAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _StatisticsCreateButton.
        /// </summary>
        public static string StatisticsCreateButton {
            get {
                return ResourceManager.GetString("StatisticsCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _StatisticsCreatePlayer.
        /// </summary>
        public static string StatisticsCreatePlayer {
            get {
                return ResourceManager.GetString("StatisticsCreatePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _StatisticsDetails.
        /// </summary>
        public static string StatisticsDetails {
            get {
                return ResourceManager.GetString("StatisticsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _StatisticsHighestOut.
        /// </summary>
        public static string StatisticsHighestOut {
            get {
                return ResourceManager.GetString("StatisticsHighestOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _StatisticsManage.
        /// </summary>
        public static string StatisticsManage {
            get {
                return ResourceManager.GetString("StatisticsManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _StatisticsRemove.
        /// </summary>
        public static string StatisticsRemove {
            get {
                return ResourceManager.GetString("StatisticsRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _StatisticsRename.
        /// </summary>
        public static string StatisticsRename {
            get {
                return ResourceManager.GetString("StatisticsRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _StatisticsTypeName.
        /// </summary>
        public static string StatisticsTypeName {
            get {
                return ResourceManager.GetString("StatisticsTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _StatisticsVictoryCount.
        /// </summary>
        public static string StatisticsVictoryCount {
            get {
                return ResourceManager.GetString("StatisticsVictoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _StatisticsYearPlaceholder.
        /// </summary>
        public static string StatisticsYearPlaceholder {
            get {
                return ResourceManager.GetString("StatisticsYearPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _MenuStats.
        /// </summary>
        public static string StatsMenu {
            get {
                return ResourceManager.GetString("StatsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _MenuStop.
        /// </summary>
        public static string StopMenu {
            get {
                return ResourceManager.GetString("StopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TournamentMain.
        /// </summary>
        public static string TournamentMain {
            get {
                return ResourceManager.GetString("TournamentMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TournamentNumPlayers.
        /// </summary>
        public static string TournamentNumPlayers {
            get {
                return ResourceManager.GetString("TournamentNumPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TournamentPlayer.
        /// </summary>
        public static string TournamentPlayer {
            get {
                return ResourceManager.GetString("TournamentPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TournamentPrepare.
        /// </summary>
        public static string TournamentPrepare {
            get {
                return ResourceManager.GetString("TournamentPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TournamentRoster.
        /// </summary>
        public static string TournamentRoster {
            get {
                return ResourceManager.GetString("TournamentRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TournamentSetupErrorPlayers.
        /// </summary>
        public static string TournamentSetupErrorPlayers {
            get {
                return ResourceManager.GetString("TournamentSetupErrorPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TrainingCheckoutThrows.
        /// </summary>
        public static string TrainingCheckoutThrows {
            get {
                return ResourceManager.GetString("TrainingCheckoutThrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TrainingDoubleThrows.
        /// </summary>
        public static string TrainingDoubleThrows {
            get {
                return ResourceManager.GetString("TrainingDoubleThrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TrainingLevel.
        /// </summary>
        public static string TrainingLevel {
            get {
                return ResourceManager.GetString("TrainingLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TrainingNotThrown.
        /// </summary>
        public static string TrainingNotThrown {
            get {
                return ResourceManager.GetString("TrainingNotThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TrainingNotThrownNext.
        /// </summary>
        public static string TrainingNotThrownNext {
            get {
                return ResourceManager.GetString("TrainingNotThrownNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TrainingRandomThrows.
        /// </summary>
        public static string TrainingRandomThrows {
            get {
                return ResourceManager.GetString("TrainingRandomThrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TrainingSingleThrows.
        /// </summary>
        public static string TrainingSingleThrows {
            get {
                return ResourceManager.GetString("TrainingSingleThrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TrainingThrown.
        /// </summary>
        public static string TrainingThrown {
            get {
                return ResourceManager.GetString("TrainingThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TrainingThrownNext.
        /// </summary>
        public static string TrainingThrownNext {
            get {
                return ResourceManager.GetString("TrainingThrownNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TrainingTotal.
        /// </summary>
        public static string TrainingTotal {
            get {
                return ResourceManager.GetString("TrainingTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TrainingTrebleThrows.
        /// </summary>
        public static string TrainingTrebleThrows {
            get {
                return ResourceManager.GetString("TrainingTrebleThrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _UpdateAvailable.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _UpdateCheck.
        /// </summary>
        public static string UpdateCheck {
            get {
                return ResourceManager.GetString("UpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _UpdateCheckFailed.
        /// </summary>
        public static string UpdateCheckFailed {
            get {
                return ResourceManager.GetString("UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _UpdateUpToDate.
        /// </summary>
        public static string UpdateUpToDate {
            get {
                return ResourceManager.GetString("UpdateUpToDate", resourceCulture);
            }
        }
    }
}
