//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopUI {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DesktopUI.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ProgName {
            get {
                return ResourceManager.GetString("ProgName", resourceCulture);
            }
        }
        
        public static string AboutAppMenu {
            get {
                return ResourceManager.GetString("AboutAppMenu", resourceCulture);
            }
        }
        
        public static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        public static string StatsMenu {
            get {
                return ResourceManager.GetString("StatsMenu", resourceCulture);
            }
        }
        
        public static string MainName {
            get {
                return ResourceManager.GetString("MainName", resourceCulture);
            }
        }
        
        public static string NumPlayers {
            get {
                return ResourceManager.GetString("NumPlayers", resourceCulture);
            }
        }
        
        public static string NumScore {
            get {
                return ResourceManager.GetString("NumScore", resourceCulture);
            }
        }
        
        public static string PlayMenu {
            get {
                return ResourceManager.GetString("PlayMenu", resourceCulture);
            }
        }
        
        public static string StopMenu {
            get {
                return ResourceManager.GetString("StopMenu", resourceCulture);
            }
        }
        
        public static string MusicMMenu {
            get {
                return ResourceManager.GetString("MusicMMenu", resourceCulture);
            }
        }
        
        public static string ButtonGameOn {
            get {
                return ResourceManager.GetString("ButtonGameOn", resourceCulture);
            }
        }
        
        public static string ButtonTraining {
            get {
                return ResourceManager.GetString("ButtonTraining", resourceCulture);
            }
        }
        
        public static string ButtonTournament {
            get {
                return ResourceManager.GetString("ButtonTournament", resourceCulture);
            }
        }
        
        public static string ButtonDetailOfTournament {
            get {
                return ResourceManager.GetString("ButtonDetailOfTournament", resourceCulture);
            }
        }
        
        public static string MenuMute {
            get {
                return ResourceManager.GetString("MenuMute", resourceCulture);
            }
        }
    }
}
