name: .NET Core Unit Tests Domain

on:
  push:
    branches: [ master , dev ]
  pull_request:
    branches: [ master , dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Assuming .NET 8.0, can be adjusted if needed

    - name: Restore dependencies
      run: dotnet restore Domain/Domain.csproj Tests/Domain.Tests/Domain.Tests.csproj

    - name: Build
      run: dotnet build Domain/Domain.csproj Tests/Domain.Tests/Domain.Tests.csproj --no-restore

    - name: Run Domain.Tests
      run: dotnet test Tests/Domain.Tests/Domain.Tests.csproj --no-build --verbosity normal
